image: ghcr.io/jethome-homeassistant/{machine}-homeassistant
build_from:
  aarch64: "ghcr.io/jethome-homeassistant/aarch64-homeassistant:"
  amd64: "ghcr.io/jethome-homeassistant/amd64-homeassistant:"
cosign:
  base_identity: https://github.com/jethome-homeassistant/core/.*
  identity: https://github.com/jethome-homeassistant/core/.*
labels:
  io.hass.type: core
  org.opencontainers.image.source: https://github.com/jethome-homeassistant/core
