image: ghcr.io/jethome-homeassistant/{machine}-homeassistant
build_from:
  aarch64: "ghcr.io/jethome-homeassistant/aarch64-homeassistant:"
  armv7: "ghcr.io/jethome-homeassistant/armv7-homeassistant:"
  armhf: "ghcr.io/jethome-homeassistant/armhf-homeassistant:"
  amd64: "ghcr.io/jethome-homeassistant/amd64-homeassistant:"
  i386: "ghcr.io/jethome-homeassistant/i386-homeassistant:"
codenotary:
  signer: vb@jethome.ru
  base_image: vb@jethome.ru
cosign:
  base_identity: https://github.com/jethome-homeassistant/core/.*
  identity: https://github.com/jethome-homeassistant/core/.*
labels:
  io.hass.type: core
  org.opencontainers.image.source: https://github.com/jethome-homeassistant/core
