image: ghcr.io/home-assistant/{machine}-homeassistant
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-homeassistant:"
  amd64: "ghcr.io/home-assistant/amd64-homeassistant:"
cosign:
  base_identity: https://github.com/home-assistant/core/.*
  identity: https://github.com/home-assistant/core/.*
labels:
  io.hass.type: core
  org.opencontainers.image.source: https://github.com/home-assistant/core
