name: JH Translations

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - dev-jethub
      - master
      - master-jethub
    paths:
      - "**strings.json"

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  upload:
    name: Upload
    if: github.repository_owner == 'jethome-homeassistant'
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: ".python-version"

      - name: Prepare Translations
        run: |
          python3 -m script.jhtranslations upload

      - name: Get translated resources from current HA core dev
        run: |
          VERSION=$(curl -s https://version.home-assistant.io/dev.json | jq -r '.homeassistant."qemuarm-64"')
          docker create --name temp-core ghcr.io/home-assistant/aarch64-homeassistant:$VERSION
          docker cp temp-core:"/usr/src/homeassistant/build/translations-download/" build/translations-download/
          docker rm temp-core

          - name: Download Translations from upstream
          run: |
            VERSION=$(curl -s https://version.home-assistant.io/beta.json | jq -r '.homeassistant."qemuarm-64"')
            docker create --name temp-core ghcr.io/home-assistant/aarch64-homeassistant:$VERSION
            docker cp temp-core:"/usr/src/homeassistant/homeassistant" ./
            docker rm temp-core

      - name: Archive translations
        shell: bash
        run: find ./homeassistant/components/*/translations -name "*.json" | tar zcvf translations.tar.gz -T -

      - name: Upload Translations
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TX_TOKEN }}
          args: push -s -t -a
